### PR TITLE
add support for HA

### LINKED ISSUE #20: Not able to configure a mesh
Hello,

with this role it is not possible to configure a mesh.
To configure a mesh each peer needs to know it's peers. The [documentation](https://github.com/prometheus/alertmanager#high-availability) says:

> --mesh.peer value: initial peers (repeat flag for each additional peer)

so I need to be able to repeat the mesh.peer flag in the role var "alertmanager_cli_flags"

I tried

```
alertmanager_cli_flags:
  mesh.peer=123.456.789.1:6783
  mesh.peer=123.456.789.2:6783
```

but only the last "mesh.peer" is passed to the cli as parameter. I looked at the code and it seems that a dictionary/map is used which always overrides the the same key with another value. That's why only the last key is passed

A workaround I found is setting a default value and passing "more":
```
alertmanager_cli_flags:
  log.level: "info --mesh.peer=123.456.789.1:6783 --mesh.peer=123.456.789.2:6783"
```

### PR DESCRIPTION
**Pull request by paulfantom**
This adds experimental support for mesh networking and resolves #20.
Example configuration is provided in defaults/main.yml

PR needs to be tested before merging. @bernhardrabe would you be able to verify if this works?

@rdemachkovych please review code.

### CODE REVIEW

**Comment by bernhardrabe** [comment]
Sure. Can you tell me how to do this with minimal effort?

**Comment by paulfantom** [comment]
Simplest way would be to define `alertmanager_mesh` with following content:
```yaml
alertmanager_mesh:
  peers:
    - "alertmanager1:6783"
    - "alertmanager2:6783"
```
and running this playbook with this role against those 2 hosts (alertmanager1, alertmanager2).

**Comment by bernhardrabe** [comment]
sorry for being not that precise. I meant: How can I use the modified role?

**Comment by paulfantom** [comment]
You can install it from github with ansible-galaxy: http://docs.ansible.com/ansible/latest/galaxy.html#version
Or by using requirements.yml file: http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file

Basically sth like:
`ansible-galaxy install git+https://github.com/cloudalchemy/ansible-alertmanager.git,issue20`

**Comment by bernhardrabe** [comment]
I can confirm that this fix works 

(though I was confused at first because I needed to use the role "ansible-alertmanager" but I think this is due to this PR)

**Comment by paulfantom** [comment]
Thanks! :+1:

**Pull request merged**
