### PR TITLE
increase systemd service security restrictions

### PR DESCRIPTION
**Pull request by paulfantom**
Loosely relates to #74

### CODE REVIEW

**Comment by dmke** [comment]
With systemd 237 on Ubuntu 18.04 LTS, I now get:

```
Aug 21 10:10:21 alertmanager.example.com systemd[1]: /etc/systemd/system/alertmanager.service:28: Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
```

**Comment by paulfantom** [comment]
Is it preventing alertmanager from starting? 

From what I know systemd should discard options it doesn't recognize and still start application but notify user about it (with log message you see). This way it accomplishes an easy path for backwards compatibility.

**Comment by dmke** [comment]
Yeah, it's just a warning, the service starts without issues (AFAICT).

**Comment by paulfantom** [comment]
Then we're good. Thanks for reporting it ;)

**Pull request merged**
