### PR TITLE
adds option to change install dir

### PR DESCRIPTION
**Pull request by wookietreiber**

### CODE REVIEW

**Comment by paulfantom** [comment]
All ansible roles in cloudalchemy try to conform to `man hier(7)` which clearly states that user-provided binaries local to an instance should be placed in `/usr/local/bin`.

Why do you need to changes this?

**Comment by wookietreiber** [comment]
It's the same reason as [here for prometheus](https://github.com/cloudalchemy/ansible-prometheus/pull/218) and [here for node-exporter](https://github.com/cloudalchemy/ansible-node-exporter/pull/137).

Both the **prometheus** and the **node-exporter** roles have the same functionality already implemented. I rely on this functionality and wanted to add this to this role to make it consistent with both **prometheus** and **node-exporter**.

**Comment by paulfantom** [comment]
Ok, so let's add it in the same way - as an unsupported variable in `vars/main.yml` without any stability guarantee. Otherwise, this cannot be accepted on the same groud as in PRs you referenced.

**Comment by paulfantom** [comment]
Sorry, I read it too fast and was thinking that you are adding this to `defaults/main.yml`.

**Pull request merged**
