### PR TITLE
New prometheus/alertmanager upstream release!

### PR DESCRIPTION
**Pull request by cloudalchemybot**
Devs at [prometheus/alertmanager](https://github.com/prometheus/alertmanager) released new software version - **0.22.0**! This automated PR updates code to bring new version into repository.

## Commit Message
create [patch] release

### CODE REVIEW

**Comment by saez0pub** [comment]
Hello,

I'm missing too an update.
Can you update to 0.22.2 ?

**Comment by SuperQ** [comment]
Hmm, tests are failing for some reason.

**Comment by pihomecloud** [comment]
Can you try to rerun the failed job ans an update to 0.22.2 ?

**Comment by saez0pub** [comment]
Can you try to rerun the failed job ans an update to 0.22.2 ?

**Comment by saez0pub** [comment]
Hello, errors have nothing with this update, is this project stil maintained ?

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**

**Pull request closed without merging**
